source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'RealmSwift', '~> 0.98'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'LKAlertController', '~> 1.7'
pod 'Timepiece', '~> 0.4'
pod 'AlamofireImage', '~> 2.0'